### ISSUE TITLE
Add Settings and Help Buttons

### ISSUE THREAD

**Issue by SirNexus** [cs361fall2017/team22#24]
This issue allocates a task to add two buttons onto our UI interface. These buttons are the Settings and Help buttons. The help button will display information for the user and the settings button will allow the user to change certain settings to the game.

**Comment by ramossy** [comment]
Task has been completed. Within the UI interface, the settings and help buttons exist in the bottom left. No functionality has been implemented. The buttons both change their background color when the user hovers over them. The css attributes for these buttons have been altered for aesthetic appeal as well.
