### ISSUE TITLE
Only Remove Aces

### ISSUE THREAD

**Issue by laurengastineau** [cs361fall2017/team22#36]
Only Aces that are located at the top of a column are able to be moved to an empty column. An empty column contains zero cards.

**Comment by SirNexus** [comment]
I think we should remove the current move button. It's slow and relatively unintuitive. In place of it I suggest we have a "Move" button appear above "Remove" and in the column in which the ace appears. When clicked the ace should be removed from its current column and placed in the empty one.

**Comment by Merfoo** [comment]
Accomplished in merge #61
