### ISSUE TITLE
Implement ability to switch between the original and Spanish version of AcesUp

### ISSUE THREAD

**Issue by SirNexus** [cs361fall2017/team22#84]
1. When you first visit the game, there will be a modal that enables the user to choose between the two game versions. 
2. Choosing the original version of AcesUp enables the user to play AcesUp with the original rules. Choosing the Spanish version of Acesup enables the user to play AcesUp with the Spanish rules. 
3. Every time the game is restarted, the modal that enables the user to choose between the two game versions is presented.

**Comment by Merfoo** [comment]
Completed in PR #96 #97 #104
